### ISSUE TITLE
Broken under Unity 2022

### ISSUE THREAD

**Issue by rhaamo** [vrchat-community/EasyQuestSwitch#22]
Installed through the creator companion, "1.2.1" from "Curated" repo.

Under Unity 2022 I can drag&drop for example a `Mesh Renderer` but can't update any Materials, drag&drop or using the select button never change it.

Tried with a fresh world created through the creator companion instead of existing project and same issue sadly.

**Comment by cbergmiller** [comment]
I'm having the same issue. No error in the console. Changing a material in the List is not possible (does nothing).

**Comment by Faxmashine** [comment]
I'm having this issue, too! EQS works *mostly*, but selecting assets to swap (or dragging and dropping) doesn't seem to work. It fails without an error.

**Comment by JordoVR** [comment]
This is now fixed in 1.3.0! 
Thank you for reporting the issue and I apologize for the delay.

**Comment by Faxmashine** [comment]
Thank you, @JordoVR ! You're the best!
